version: "3"
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.3
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=${TLS_CERT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      # The HTTP port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # just mount it and magic will happen
      - "./letsencrypt:/letsencrypt"

  server:
    build:
      .
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    environment:
        DEBUG: "speckle:*"
    env_file:
      - .env
    labels:
    - "traefik.http.routers.server.rule=Host(`${CANONICAL_URL}`)"
    - "traefik.enable=true"
    - "traefik.http.routers.server.entrypoints=websecure"
    - "traefik.http.routers.server.tls.certresolver=myresolver"
    
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - .env # configure postgres
    volumes:
      # persist data even if container shuts down
      - speckle-postgres-data:/var/lib/postgresql/data/
      # this mounts the initdb folder to the db container
      # .sql .sh files are executed from this folder in alphabetical order
      - ./initdb:/docker-entrypoint-initdb.d  
    ports:
      - "5432:5432"

  redis:
    image: "redis"
    # ports:
    #   - "6379:6379" # It is not neccesary to expose the reddis port if running the app with compose 
    volumes:
      - redis_volume_data:/data

volumes:
# named volumes can be managed easier using docker-compose
  speckle-postgres-data: 
  redis_volume_data: